name: Package deployment

on:
  release:
    types: [published]

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm ci
      - name: Build lib
        run: npm run build:lib
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with: 
          name: dist
          path: ./
          retention-days: 2
  
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
