name: Package deployment

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm ci
      - name: Build dist
        run: npm run build:dist
      - name: Create package
        shell: bash
        run: |
          tar czf package.tgz * .??*
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with: 
          name: package
          path: package.tgz
          retention-days: 2
  
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package
      - name: Unzip package
        shell: bash
        run: |
          tar xzf package.tgz
      - name: Publish to npm
        run: npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
