name: Quality Assurance

on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm test
  
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test:cov